Global:
  Source: "cui--新值222"
  LogLevel: "info"
  ChangeMe: "v3"

Server:
  Address: "127.0.0.11"
  Port: 18080

Client:
  Echo: false
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
LANG: "山东话"